// @flow

import faker from 'faker'

const table = () => ({
  key: 'contentTag',
  tableName: 'ContentTags',
  foreignKeys: {
    userId: ['Users', 'id'],
    tagId: ['Tags', 'name'],
    contentId: ['Content', 'id']
  },
  columns: {
    createdAt: faker.date.past(),
    updatedAt: faker.date.past(),
    confidence: Math.floor(Math.random() * 1000) / 1000,
    autogenerated: faker.random.boolean()
  }
})

export default table
