// @flow

import faker from 'faker'

const table = () => ({
  key: 'contentTag',
  tableName: 'ContentTags',
  foreignKeys: {
    userId: ['Users', 'id'],
    tagId: ['Tags', 'name'],
    contentId: ['Content', 'id']
  },
  columns: {
    createdAt: faker.date.past(),
    updatedAt: faker.date.past(),
    confidence: faker.random.number({ min: 0, max: 1, precision: 0.001 }),
    autogenerated: faker.random.boolean()
  }
})

export default table
